filebeat.inputs:
- type: log #Change value to true to activate the input configuration
  enabled: true
  paths:
    - /usr/share/filebeat/logs/*.log
output.logstash:
  # The Logstash hosts
  hosts: ["logstash:5000"]
